### ISSUE TITLE
Validate your html code

### ISSUE THREAD

**Issue by Theophile-Kango** [menyagah/youTube_clone#2]
Your page is structured very well but you have only to validate your HTML code 
The frameborder attribute on the iframe element is obsolete. Use CSS instead.

From line 41, column 13; to line 41, column 205

          <iframe width="853" height="480" src="https://www.youtube.com/embed/vpD0k9oebI4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

**Comment by Morrism1** [comment]
I removed the frameborder attribute now
